Configuration
thelotter-enterprise/corego pull request #2
Opened 2020-11-02 13:39 UTC by danielcNet-bet

2020-11-02 15:27 UTC, kolbis requested changes
// 1.
	// I want to load the config from volume: 
	// ./config/conf1.yaml
	// ./config/conf2.json 
	// iterate over all the config files, push them to remote and append thm to viper

	// 2.
	// I want to iterate on all the env variables, puish them to remote and load them into viper

	// 3. 
	// Getting the config from consul KV and load them into viper

	configClient.AddEnv() 
	configClient.AddFileSource(configFileYAML)
	configClient.AddFileSource(configFileJson) // if same config from other files, you dont know how to take decision so you panic
	configClient.AddRemoteSource(consulKVProvider) // source of truth
	configClient.Load() // map[string]interface{} // map[string]string --> upload to remote and load viper
                                   
	options := {
	}

	configValue := configClient.Get("new_check_win", ...options)

2020-11-03 15:51 UTC, kolbis requested changes
Looks good
I would like to see more tests for the merge functionality
There is a lot of logic to cover in these tests which I am missing here.

2020-11-04 15:20 UTC, kolbis requested changes
Still need tests

2020-11-04 15:20 UTC, kolbis commented on configuration/configuration_integration_test.go
> +	if isIntegrationTest {
why do you have a condition for isIntegrationTest? You are in integration file....

2020-11-04 15:20 UTC, kolbis commented on configuration/configuration_test.go
> +func TestMergeValues(t *testing.T) {
you are missing with a core test:
- assuming you have the same value on remote and on local, remote wins
- when two different keys exist, both should be in the merge

2020-11-04 15:47 UTC, danielcNet-bet commented on configuration/configuration_test.go
> +func TestMergeValues(t *testing.T) {
@kolbis regarding "remote wins" that is true , BUT only one thet marked as source, all other remotes will be merged same as file or env variables.
The logic is if Remote provider marked as final source - we are not going to merge his config with other configs. 
Only when all configs merged -> we matching all values(between source config and merged list) and if value not exists in source remote provider -> push it.(this part is still in TODO because we missing consul implementation)
Then we telling viper to  synchronize with remote source.

2020-11-04 16:04 UTC, danielcNet-bet commented on configuration/configuration_integration_test.go
> +	if isIntegrationTest {
@kolbis we do not want run an integration tests each time we run go test
For example if I have some request to the db or consul or rabbit or something else - in my local I got prepared set up , but other dev - not. Also i do not want to run integration tests in CI build , but I want to run tests

2020-11-09 07:15 UTC, kolbis requested changes

2020-11-09 07:15 UTC, kolbis commented on kv/service.go
> +	GetStringMap(string, MapFormat, map[string]interface{}) map[string]interface{}
I dont think this should be part of the interface. To me it seems like utilities function which will be the same of each KV config provider we implement.

I would expect a function:
func GetValye(string, default) interface{}

2020-11-09 07:15 UTC, kolbis commented on kv/service.go
> +	Get(string, KeyValueReader) (interface{}, error)
The consumer should not care how the data is stored.
He is saying: give me the config name "key1"

I think there are two different contracts here:
KVLoader which is responsible to read the configurations
KV which is responsible to interact with the configurations once they are loaded

2020-11-09 07:15 UTC, kolbis commented on kv/consul.go
> +func ReadAsJSON(byteArray []byte) (interface{}, error) {
not consul concern. should be placed on a different file

2020-11-09 12:27 UTC, danielcNet-bet commented on kv/service.go
> +	GetStringMap(string, MapFormat, map[string]interface{}) map[string]interface{}
@kolbis  Here I disagree with you
That assigned to our discussion few days ago "Make client experience easy as much as it possible" .
Consul provide to us API that return []byte - and all we know about this array - that it can be decode as ascii. We do not know if value is int or json or yaml etc. 
How it affect the client - client will be required to make additional cast in his side with using 3-rd party lib`s.

Maybe we can split it to 2 interfaces KV only with Get function and KVHelper or KVClient for all other functions.

Anyway I think we need to  discourse about it before I continue.

2020-11-11 11:01 UTC, kolbis requested changes

2020-11-11 11:01 UTC, kolbis commented on configuration/configuration.go
> +	GetString(string, string) string
Create a util.go and inside place all the convert functions:
config.GetString("")

2020-11-11 11:01 UTC, kolbis commented on configuration/configuration.go
> +		err = errors.New(errorMessage)
dont use error.New
I would create a configurationError and use it

2020-11-12 06:47 UTC, merged